# Let's explore the dataset of Pakistan Super League (PSL).
### Dataset file name is `PSL.csv` and contains data from 2016 to 2025

# Reading the dataset and showing the number of Rows and Columns

In [1]:
import pandas as pd
df = pd.read_csv("PSL.csv") # change it accordingly
df.shape

(321, 14)

# Printing first 10 rows

In [2]:
df.head()

,Team1,Team2,Team1 Score,Team2 Score,Team1 Wickets,Team2 Wickets,Team1 Overs,Team2 Overs,Toss Won,Decided to,Date,Month,Year,Won
0,Lahore Qalandars,Karachi Kings,125,131.0,8,3.0,20.0,15.5,Karachi Kings,Bowl,5,February,2016,Karachi Kings
1,Peshawar Zalmi,Islamabad United,145,121.0,7,9.0,20.0,20.0,Peshawar Zalmi,Bat,5,February,2016,Peshawar Zalmi
2,Karachi Kings,Quetta Gladiators,147,153.0,7,2.0,20.0,17.2,Quetta Gladiators,Bowl,6,February,2016,Quetta Gladiators
3,Lahore Qalandars,Peshawar Zalmi,117,118.0,6,1.0,20.0,16.0,Peshawar Zalmi,Bowl,6,February,2016,Peshawar Zalmi
4,Islamabad United,Karachi Kings,132,139.0,8,7.0,20.0,19.5,Islamabad United,Bat,7,February,2016,Karachi Kings

# Printing columns

In [3]:
df.columns

Index(['Team1', 'Team2', 'Team1 Score', 'Team2 Score', 'Team1 Wickets',
       'Team2 Wickets', 'Team1 Overs', 'Team2 Overs', 'Toss Won', 'Decided to',
       'Date', 'Month', 'Year', 'Won'],
      dtype='object')

# Printing basic stats of the dataset

In [4]:
df.describe()

,Team1 Score,Team2 Score,Team1 Wickets,Team2 Wickets,Team1 Overs,Team2 Overs,Date,Year
count,321.000000,315.000000,321.000000,315.000000,321.000000,315.000000,321.000000,321.000000
mean,165.451713,154.174603,6.236760,6.180952,19.221184,18.206349,15.420561,2020.753894
std,38.726747,35.238649,2.345212,2.859049,2.860035,2.838782,7.960886,2.763353
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2016.000000
25%,147.000000,135.000000,5.000000,4.000000,20.000000,17.750000,9.000000,2018.000000
50%,168.000000,157.000000,6.000000,6.000000,20.000000,19.200000,16.000000,2021.000000
75%,188.000000,176.000000,8.000000,9.000000,20.000000,20.000000,22.000000,2023.000000
max,263.000000,253.000000,10.000000,10.000000,20.000000,20.000000,31.000000,2025.000000

# Finding null values

In [7]:
df.isnull().sum()

Team1            1
Team2            6
Team1 Score      0
Team2 Score      6
Team1 Wickets    0
Team2 Wickets    6
Team1 Overs      0
Team2 Overs      6
Toss Won         4
Decided to       4
Date             0
Month            0
Year             0
Won              2
dtype: int64

# Printing all rows which are null
### Most of the time these are matches which abandoned due to rain or maybe another reason. It's your choice whether you discard them or keep them and fill using method like mean/mode.
## It is recommend to discard them since they are very few in numbers

In [8]:
df[df.isnull().any(axis=1)]

,Team1,Team2,Team1 Score,Team2 Score,Team1 Wickets,Team2 Wickets,Team1 Overs,Team2 Overs,Toss Won,Decided to,Date,Month,Year,Won
129,NaN,NaN,0,NaN,0,NaN,0.0,NaN,NaN,NaN,29,February,2020,No result
135,Multan Sultans,NaN,102,NaN,6,NaN,16.5,NaN,Karachi Kings,Bowl,6,March,2020,No result
141,Innings,NaN,0,NaN,0,NaN,0.0,NaN,NaN,NaN,11,March,2020,No result
269,Innings,NaN,0,NaN,0,NaN,0.0,NaN,NaN,NaN,2,March,2024,NaN
270,Innings,NaN,0,NaN,0,NaN,0.0,NaN,NaN,NaN,2,March,2024,NaN
307,Lahore Qalandars,NaN,111,NaN,3,NaN,11.3,NaN,Quetta Gladiators,Bowl,1,May\n,2025,No result

# Dropping null rows and printing dimensions

In [13]:
df = df.dropna()
df.shape

(315, 14)

# Now you're ready to use this dataset for ML/AI tasks.
### Want to report or contribute? Open issue or pull request on [100 Datasets](https://github.com/Ahtisham-1214/100-Datasets)
#### Thanks to our contributors [Anees Ahmed](https://github.com/i-AneesAhmed) [Neha Baviskar](https://github.com/nehabaviskar1997)